# Source S3 Configuration
source_s3:
  endpoint: "192.168.199.211:9000"
  access_key: "AKIAIOSFODNN7EXAMPLE"
  secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  bucket: "test1"
  prefix: "ws"
  use_ssl: false

# Destination S3 Configuration
destination_s3:
  endpoint: "192.168.199.212:9000"
  access_key: "AKIAIOSFODNN7EXAMPLE"
  secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  bucket: "test2"
  use_ssl: false

# Migration Specific Settings
migration:
  concurrency: 2
  db_path: "migration_progress.db"

# Logging Settings
logging:
  level: "info"
  output_file: "migration.log"
  format: "text"