# Source S3 Configuration
source_s3:
  endpoint: "192.168.199.211:9000"
  access_key: "AKIAIOSFODNN7EXAMPLE"
  secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  bucket: "test1"
  prefix: "ws"
  use_ssl: false

# Destination S3 Configuration
destination_s3:
  endpoint: "192.168.199.212:9000"
  access_key: "AKIAIOSFODNN7EXAMPLE"
  secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  bucket: "test3"
  use_ssl: false

# Migration Specific Settings
migration:
  concurrency: 2
  dbpath: "migration_progress.db"
  localpath: "D:/dev/go/oos"
  filelist: "files.txt"
  tolocal: true


# Logging Settings
logging:
  level: "info"
  output_file: "migration.log"
  format: "text"